version: "2.1"
services:
    authserver_db:
        image: mcr.microsoft.com/mssql/server:2019-latest
        networks:
            - planthere_network
    
    planthere_db:
        image: mcr.microsoft.com/mssql/server:2019-latest
        networks:
            - planthere_network
    
    rabbitmq:
        image: rabbitmq:3-management

    redis:
        image: redis:latest

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0

    authserver_api:
        image: authserver
        build:
            context: .
            dockerfile: AuthServer/Dockerfile
        networks:
            - planthere_network
    
    planthere_dotnet_api:
        image: planthere_dotnet
        build:
            context: .
            dockerfile: PlantHere/Dockerfile
        networks:
            - planthere_network

    planthere_nodejs_api:
        image: planthere_nodejs
        build:
            context: .
            dockerfile: PlantHereNodejs/Dockerfile
        networks:
            - planthere_network
   
    reactjs_ui:
        image: ui
        build: 
            context: .
            dockerfile: PlantHereReactJs/Dockerfile

networks:
  planthere_network:
    driver: bridge
    
volumes:
  authserver_db_volume:
  planthere_db_volume:
  esdata: