@BaseUrl = http://localhost:4000/
@BaseUrlDotNet  = https://localhost:44391/


###
GET {{BaseUrl}}Category

###
GET {{BaseUrl}}Category/2
Content-Type: application/json

{
  
}

###
POST  {{BaseUrl}}Category
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjgxYmZjMjBhLTlhMjgtNDkwNC04ZmNiLTEyZjQ0Y2NjNzUxOSIsImVtYWlsIjoic3VwZXJhZG1pbkBnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoic3VwZXJhZG1pbiIsImp0aSI6ImI4ZmM1ZjM4LTk0M2MtNGNiNy1hMTBmLTBjZjgwY2Y5ZGM5ZiIsImF1ZCI6WyJ3d3cucGxhbnRoZXJlLmNvbSIsInd3dy50cmFkZS5jb20iXSwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjpbInN1cGVyYWRtaW4iLCJzZWxsZXIiXSwibmJmIjoxNjcxMTgzMDAxLCJleHAiOjE2NzE3ODMwMDEsImlzcyI6Ind3dy5hdXRoc2VydmVyLmNvbSJ9.ahMi6zzdOfoGfaz4_lTNI2_Ym19gfMtga_5yvTGXUqk
Content-Type: application/json

{
    "nameTr" :"Salon Bitkisi",
    "nameEn" : "Hall Plant"
}

###
PUT   {{BaseUrl}}Category
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjgxYmZjMjBhLTlhMjgtNDkwNC04ZmNiLTEyZjQ0Y2NjNzUxOSIsImVtYWlsIjoic3VwZXJhZG1pbkBnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoic3VwZXJhZG1pbiIsImp0aSI6ImI4ZmM1ZjM4LTk0M2MtNGNiNy1hMTBmLTBjZjgwY2Y5ZGM5ZiIsImF1ZCI6WyJ3d3cucGxhbnRoZXJlLmNvbSIsInd3dy50cmFkZS5jb20iXSwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjpbInN1cGVyYWRtaW4iLCJzZWxsZXIiXSwibmJmIjoxNjcxMTgzMDAxLCJleHAiOjE2NzE3ODMwMDEsImlzcyI6Ind3dy5hdXRoc2VydmVyLmNvbSJ9.ahMi6zzdOfoGfaz4_lTNI2_Ym19gfMtga_5yvTGXUqk
Content-Type: application/json

{
    "id" : 4,
    "nameTr" :"Salon Bitkisi",
    "nameEn" : "Hall Plant"
}


###
DELETE {{BaseUrl}}Category
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjgxYmZjMjBhLTlhMjgtNDkwNC04ZmNiLTEyZjQ0Y2NjNzUxOSIsImVtYWlsIjoic3VwZXJhZG1pbkBnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoic3VwZXJhZG1pbiIsImp0aSI6ImI4ZmM1ZjM4LTk0M2MtNGNiNy1hMTBmLTBjZjgwY2Y5ZGM5ZiIsImF1ZCI6WyJ3d3cucGxhbnRoZXJlLmNvbSIsInd3dy50cmFkZS5jb20iXSwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjpbInN1cGVyYWRtaW4iLCJzZWxsZXIiXSwibmJmIjoxNjcxMTgzMDAxLCJleHAiOjE2NzE3ODMwMDEsImlzcyI6Ind3dy5hdXRoc2VydmVyLmNvbSJ9.ahMi6zzdOfoGfaz4_lTNI2_Ym19gfMtga_5yvTGXUqk
Content-Type: application/json

{
    "id" : 4
}